### ISSUE TITLE
Gitter8 project template with scalazzi , wartremover, scalafmt etc. (with same configurations as toolkit has) 

### ISSUE THREAD

**Issue by strobe** [avast/scala-server-toolkit#130]
You already have a set of valuable practices implemented in sbt configuration like  scalazzi , wartremover, scalafmt, mdoc etc. Those things might be very useful as the nice default configuration for projects that will use scala-server-toolkit as libraries. And it probably helps to implement new modules at derived projects with same style that toolkit has, so it will be easiest to contribute that back to toolkit repo. 

Do you consider to create gitter8 template with that configuration (for example like Http4s has at website).  As an alternative probably you may create a small example app project which will be used as starting point for all documentation and blog examples.

**Comment by jakubjanecek** [comment]
Hello, yes, I do have something like that in my TODO. Anyone is encouraged to give it a try ;)

**Comment by strobe** [comment]
I created the gitter8 template project https://github.com/strobe/sst-seed.g8, please check out.

**Comment by jakubjanecek** [comment]
Hi, looks pretty good. Thank you! Would you be willing to contribute this to `avast` namespace so that it is more official? That way it could also go through the usual PR process where I could comment on some parts.

**Comment by strobe** [comment]
yes, I ready to transfer that repo to 'avast' namespace or push same content to new repo. What I have to do for that?

**Comment by jakubjanecek** [comment]
Great. Can you please make a pull request into this repo then? (make a fork of that repo and submit a PR from your branch)

https://github.com/avast/sst-seed

**Comment by strobe** [comment]
please add any file to that repo - seems is not possible to fork it if no files in repo

**Comment by jakubjanecek** [comment]
README added.

**Comment by strobe** [comment]
I created [PR](https://github.com/avast/sst-seed/pull/1).

Also seems current repo naming convention around Gitter8 is a <repo_name>.g8 so seems is a good idea to rename your repo to  sst-seed.g8

**Comment by jakubjanecek** [comment]
Thank you for your contribution. Highly appreciated.
