### ISSUE TITLE
Add module for Kafka

### ISSUE THREAD

**Issue by jakubjanecek** [avast/scala-server-toolkit#67]
We should support initialization of Kafka client.

**Comment by Hoffmannxd** [comment]
You think monix-kafka is a good candidate since its already wrapped into an effect?

**Comment by jakubjanecek** [comment]
Hello Matheus,
`monix-kafka` works only with Monix `Task` and that is not a good option for us since we want to support any `cats-effect` data type (such as Monix `Task`, ZIO and possibly others).

I've done some googling around Scala Kafka clients and there does not seem to be too many options. The only two I see viable are https://github.com/cakesolutions/scala-kafka-client/ and https://github.com/Banno/kafka4s (considering what they offer, how maintained and active they are, etc.). Just from a brief look I subjectively prefer the `scala-kafka-client`.

Another option is to provide only initialization module for the official Java driver and we can let people wrap it their own way. Or we can do both - provide the official Java driver and one of the Scala clients.

What do you think? Would you like to give it a try?

**Comment by Hoffmannxd** [comment]
I think you're correct. One of the features that i liked in monix kafka to is the typed configuration since in the java api you have to write lots of strings manually. About the effects, for what i understood you want that should be wrapped over an abstract F with type classes constraints. Personally i`m starting right now using pure FP but i can give a try.

**Comment by jakubjanecek** [comment]
Matheus, typed configuration is one of the core features of Scala Server Toolkit. We provide it even for components that do not have it out-of-the-box. So the underlying client does not have to provide it, that's what we do. And yes, you want to wrap it in abstract `F` with `Sync` (or other) typeclass constraint.

Anyway, give it a try! No one is currently working on this issue so it would be awesome to get your contribution. Try to use the `scala-kafka-client` from Cake Solutions, I think that's a better option.

I encourage you to read the [CONTRIBUTING](https://github.com/avast/scala-server-toolkit/blob/master/CONTRIBUTING.md) guide and maybe also parts of the [documentation](https://github.com/avast/scala-server-toolkit/blob/master/docs/index.md). It's always good to look at already existing components to see how it should be done.

I am here for you in case you need any help. You can contact me here or via e-mail at `janecek.jakub at gmail.com`.

What you should start with is something like `object ScalaKafkaClientModule` with method `make` and `case class ScalaKafkaClientConfig` which will contain the entire configuration hierarchy for the client (with all the possible configuration options).

Thank you and let me know how it goes.

**Comment by Hoffmannxd** [comment]
Its ok! I will give a try, thanks for the support.

**Comment by sideeffffect** [comment]
Have we considered using https://fd4s.github.io/fs2-kafka/?

**Comment by jakubjanecek** [comment]
I haven't found that before. I think we can have both. I like that `scala-kafka-client` is quite low-level which can be useful sometimes and it is good as a building block.

**Comment by jakubjanecek** [comment]
I'm taking over this issue because I need Kafka client so I will implement it. I've decided to use the `fs2-kafka` client as it seems quite nice.
