### ISSUE TITLE
New module cats-effect-interop-java

### ISSUE THREAD

**Issue by sideeffffect** [avast/scala-server-toolkit#87]
I propose to add a new module `cats-effect-interop-java`, which (as the name suggests) is to be used for interoperability between `cats-effect` and Java's concurrency primitives, like [`CompletionStage`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletionStage.html), [`CompletionHandler`](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/CompletionHandler.html), etc.

For inspiration: https://github.com/zio/interop-java/blob/master/src/main/scala/zio/interop/javaz.scala#L65

We can eventually spin it off to it's own repo, but this place could be a suitable nursery. There could be also many other `cats-effect-interop-*` modues, like for Guava, Scala's Future or whatever; apparently there's a big thirst for these kind of small interop libraries (see for example here https://github.com/typelevel/cats-effect/issues/160).

**Comment by jakubjanecek** [comment]
I think this should be a standalone library that can possibly be used by SST. I don't want SST to become nursery for experimantal stuff, the other way around yes.

**Comment by sideeffffect** [comment]
fair enough

**Comment by tovbinm** [comment]
Did this ever become a library that was released?

**Comment by jakubjanecek** [comment]
I don't think so. We haven't needed such thing.
